version: 2
jobs:
    build:
        docker:
            - image: theorangeone/docker-pandoc
        working_directory: ~/smallpeice-rules/
        steps:
            - checkout
            - run: apk add ghostscript
            - run:
                name: Install Submodules
                command: git submodule sync && git submodule update --init
            - run: make
            - store_artifacts:
                path: rules.pdf
                destination: rules.pdf
